### ISSUE TITLE
默认代码高亮

### ISSUE THREAD

**Issue by Thysrael** [xuchunyang/shr-tag-pre-highlight.el#3]
您好，非常感谢您开发了这个功能，请问有没有一种方法可以在识别不出代码类型的情况下，默认代码为某一种呀？（比如说 C++）

我在使用 eww 阅读文档的时候，发现无法识别语言，但是其实只要有默认语言功能，就可以解决大部分的无法识别问题。请问有办法设置吗？

**Comment by xuchunyang** [comment]
请尝试 Advice 相关函数，比如：

```elisp
(define-advice shr-tag-pre-highlight-guess-language-attr (:filter-return (&rest r) fallback-to-cpp)
  "如果检测不出来哪种语言，默认 C++."
  (or (car r) "C++"))
```

> [!WARNING]  
> 我没有亲自试过上述代码，我大概三年没用 Emacs 了，但是我感觉是这样写的。

**Comment by Thysrael** [comment]
> ```emacs-lisp
> (define-advice shr-tag-pre-highlight-guess-language-attr (:filter-return (&rest r) fallback-to-cpp)
>   "如果检测不出来哪种语言，默认 C++."
>   (or (car r) "C++"))
> ```

太感谢了，只需要把 "C++" 改成 "c++" 就可以用了，谢谢您

**Comment by Thysrael** [comment]
另外您知道为什么这个[网站](https://changkun.de/modern-cpp/zh-cn/03-runtime/)不可以吗？我注意到您的包的机制似乎是搜索 html 文件里的 pre 块，上面这个网站里也有 pre 块，但是好像却没法正常渲染，好像甚至都没有被识别成代码块。

在我这里是这样的

![image](https://github.com/xuchunyang/shr-tag-pre-highlight.el/assets/72613958/8ee99825-5eda-4cc7-8c08-26582c69f4d6)

如果是识别成代码块而无法识别语言，似乎是这样的

![image](https://github.com/xuchunyang/shr-tag-pre-highlight.el/assets/72613958/4919412e-39a7-4913-a370-593b36249c82)

总之非常感谢您，麻烦您了。

**Comment by xuchunyang** [comment]
> 另外您知道为什么这个[网站](https://changkun.de/modern-cpp/zh-cn/03-runtime/)不可以吗？

我试了下，我这儿的 EWW 正常的，看你的截图，你的 EWW 应该是高度定制过的，或许你的配置有问题？可以检查 `shr-external-rendering-functions` 变量看看

![CleanShot 2023-12-09 at 07 53 19@2x](https://github.com/xuchunyang/shr-tag-pre-highlight.el/assets/4550353/0bfa72be-1174-4ee9-8dd2-616a083acb14)

> 我注意到您的包的机制似乎是搜索 html 文件里的 pre 块

你的观察没错，`shr-external-rendering-functions` 变量让用户/第三方包自定义各种标签的渲染，比如 shr-tag-pre-highlight.el 这个包就是加代码高亮，这个 pre 标签的是 EWW 自身解析出来的。

**Comment by Thysrael** [comment]
`shr-external-rendering-functions` 是

```emacs-lisp
Value:
((code . shrface-tag-code)
 (figure . shrface-tag-figure)
 (dt . shrface-tag-dt)
 (li . shrface-tag-li)
 (p . shrface-tag-p)
 (a . shrface-tag-a)
 (h6 . shrface-tag-h6)
 (h5 . shrface-tag-h5)
 (h4 . shrface-tag-h4)
 (h3 . shrface-tag-h3)
 (h2 . shrface-tag-h2)
 (h1 . shrface-tag-h1)
 (svg . shrface-tag-svg)
 (strong . shrface-tag-strong)
 (u . shrface-tag-u)
 (em . shrface-tag-em)
 (pre . shr-tag-pre-highlight))
```

我目前的配置是

```emacs-lisp
;;; 浏览器
;; 内置浏览器
(use-package eww
  :init
  (add-hook 'eww-after-render-hook #'shrface-mode)
  :config
  (require 'shrface)
  (setq eww-retrieve-command '("readable") ; 只提取页面的可阅读部分
        shr-max-image-proportion 0.6)
  (defun +toggle-eww ()
    "Open eww if not already open, and switch to the *eww* buffer."
    (interactive)
    ;; Check if eww is already open
    (if (get-buffer "*eww*")
        ;; If *eww* buffer exists, switch to it
        (switch-to-buffer "*eww*")
      ;; If *eww* buffer doesn't exist, open eww
      (let ((url (read-string "Enter URL: ")))
        (eww url))))
  :hook
  (eww-mode . (lambda () (progn
                      (setq line-spacing 0.15) ; 行间距扩大
                      (setq fill-column 140) ; 更宽的阅读视界
                      (setq truncate-lines nil) ; 自动折行
                      )
                ))
  :bind
  ("C-c w" . +toggle-eww)
  ("C-c W" . eww-list-bookmarks)
  (:map eww-mode-map
        ("j" . next-line)
        ("k" . previous-line)
        ("l" . +smart-forward)
        ("h" . backward-char)
        ("i" . eww-toggle-images)
        ("o" . maple-translate)
        ("m" . set-mark-command)
        ("," . eww-back-url)
        ("." . eww-forward-url))
  )

;; 将页面渲染成 org-mode
(use-package shrface
  :config
  (shrface-basic)
  (shrface-trial)
  (shrface-default-keybindings) ; setup default keybindings
  (setq shrface-href-versatile t)
  :bind
  (:map shrface-mode-map
        ("n" . shrface-next-headline)
        ("p" . shrface-previous-headline)))
;; 设置代码字体，不知道为什么不能写进去
(custom-set-faces '(shrface-code ((t (:inherit org-code :family "JetBrainsMono Nerd Font")))))

(use-package shr-tag-pre-highlight
  :after shr
  :init
  (require 'shr-tag-pre-highlight)
  (add-to-list 'shr-external-rendering-functions
               '(pre . shr-tag-pre-highlight))
  (define-advice shr-tag-pre-highlight-guess-language-attr (:filter-return (&rest r) fallback-to-cpp)
    "如果检测不出来哪种语言，默认 C++."
    (or (car r) "c++-ts"))
```
我捣鼓了一下，并没有办法修好，即使去掉其他配置，似乎也不行。非常感谢您，就不麻烦您了，感谢。

**Comment by xuchunyang** [comment]
> ```emacs-lisp
>   (setq eww-retrieve-command '("readable") ; 只提取页面的可阅读部分
> ```

可能标签都被这个命令处理掉了，你可以去掉试试。

> 我捣鼓了一下，并没有办法修好，即使去掉其他配置，似乎也不行。非常感谢您，就不麻烦您了，感谢。

你可以试试到 https://emacs-china.org/ 寻求帮助，我相信不难解决的。
